# Generated by Django 4.2.14 on 2024-07-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_images_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.PositiveIntegerField()),
                ('projects', models.PositiveIntegerField()),
                ('hours_of_support', models.PositiveIntegerField()),
                ('hard_workers', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='factImages/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clientImages/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Our Clients',
                'verbose_name_plural': 'Our Clients',
            },
        ),
        migrations.CreateModel(
            name='OurRecentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recentworkImages/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Our Recent Work',
                'verbose_name_plural': 'Our Recent Work',
            },
        ),
        migrations.CreateModel(
            name='OurSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('percent', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Our Skills',
                'verbose_name_plural': 'Our Skills',
            },
        ),
    ]
