# Generated by Django 4.2.14 on 2024-07-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='short_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
