# Generated by Django 4.2.14 on 2024-07-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_services_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='cover_image',
            field=models.ImageField(default='', upload_to='services/'),
        ),
    ]
