# Generated by Django 4.2.14 on 2024-07-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_services_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
    ]
