# Generated by Django 4.2.14 on 2024-07-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='servicesimages/')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_images', to='service.services')),
            ],
            options={
                'verbose_name': 'Services Images ',
                'verbose_name_plural': 'Services Images ',
            },
        ),
    ]
