# Generated by Django 4.2.14 on 2024-07-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='short_description',
            field=models.TextField(max_length=1000, verbose_name='short description'),
        ),
    ]
