# Generated by Django 4.2.14 on 2024-07-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_cover',
            field=models.ImageField(default='', upload_to='about/'),
            preserve_default=False,
        ),
    ]
