# Generated by Django 4.2.14 on 2024-07-16 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blinds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=5000)),
                ('description', models.TextField(max_length=100000, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('image', models.ImageField(upload_to='blinds/')),
            ],
            options={
                'verbose_name': 'Blinds',
                'verbose_name_plural': 'Blinds',
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=5000)),
                ('description', models.TextField(max_length=100000, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('image', models.ImageField(upload_to='commercial/')),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commercial',
            },
        ),
        migrations.CreateModel(
            name='Curtains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=5000)),
                ('description', models.TextField(max_length=100000, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('image', models.ImageField(upload_to='curtains/')),
            ],
            options={
                'verbose_name': 'Curtains',
                'verbose_name_plural': 'Curtains',
            },
        ),
        migrations.CreateModel(
            name='MotorizedBlinds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=5000)),
                ('description', models.TextField(max_length=100000, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('image', models.ImageField(upload_to='motorized-blinds/')),
            ],
            options={
                'verbose_name': 'MotorizedBlinds',
                'verbose_name_plural': 'MotorizedBlinds',
            },
        ),
        migrations.CreateModel(
            name='MotorizedBlindsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motorizedblindsimages/')),
                ('motorizedblinds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorizedblinds_images', to='products.motorizedblinds')),
            ],
        ),
        migrations.CreateModel(
            name='CurtainsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='curtainsimages/')),
                ('curtains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtains_images', to='products.curtains')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commercialimages/')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_images', to='products.commercial')),
            ],
        ),
        migrations.CreateModel(
            name='BlindImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blindimages/')),
                ('blind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_images', to='products.blinds')),
            ],
        ),
    ]
