# Generated by Django 4.2.14 on 2024-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blinds',
            name='title',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='title',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='curtains',
            name='title',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='motorizedblinds',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
