# Generated by Django 4.2.14 on 2024-07-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_blinds_title_alter_commercial_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blinds',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercial',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curtains',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorizedblinds',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
