# Generated by Django 4.2.14 on 2024-07-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_blinds_slug_commercial_slug_curtains_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blindimages',
            options={'verbose_name': 'Blind Images', 'verbose_name_plural': 'Blind Images'},
        ),
        migrations.AlterModelOptions(
            name='commercialimages',
            options={'verbose_name': 'Commercial Images', 'verbose_name_plural': 'Commercial Images'},
        ),
        migrations.AlterModelOptions(
            name='curtainsimages',
            options={'verbose_name': 'Curtains Images', 'verbose_name_plural': 'Curtains Images'},
        ),
        migrations.AlterModelOptions(
            name='motorizedblindsimages',
            options={'verbose_name': 'MotorizedBlinds Images', 'verbose_name_plural': 'MotorizedBlinds Images'},
        ),
    ]
