# Generated by Django 4.2.14 on 2024-07-19 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_blindimages_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('description', models.TextField(max_length=100000, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('image', models.ImageField(upload_to='accessories/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Accessories',
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='FurnitureClassic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('description', models.TextField(max_length=100000, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('image', models.ImageField(upload_to='FurnitureClassic/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Furniture Classic',
                'verbose_name_plural': 'Furniture Classic',
            },
        ),
        migrations.CreateModel(
            name='FurnitureModern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('description', models.TextField(max_length=100000, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('image', models.ImageField(upload_to='FurnitureModern/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Furniture Modern',
                'verbose_name_plural': 'Furniture Modern',
            },
        ),
        migrations.CreateModel(
            name='FurnitureModernImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='FurnitureModernimages/')),
                ('modern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modern_images', to='products.furnituremodern')),
            ],
            options={
                'verbose_name': 'FurnitureModern Images',
                'verbose_name_plural': 'FurnitureModern Images',
            },
        ),
        migrations.CreateModel(
            name='FurnitureClassicImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='FurnitureClassicimages/')),
                ('classic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classic_images', to='products.furnitureclassic')),
            ],
            options={
                'verbose_name': 'FurnitureClassic Images',
                'verbose_name_plural': 'FurnitureClassic Images',
            },
        ),
        migrations.CreateModel(
            name='AccessoriesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accessoriesimages/')),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_images', to='products.accessories')),
            ],
            options={
                'verbose_name': 'Accessories Images ',
                'verbose_name_plural': 'Accessories Images ',
            },
        ),
    ]
