# Generated by Django 4.2.14 on 2024-07-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_accessories_furnitureclassic_furnituremodern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnitureclassicimages',
            name='classic',
        ),
        migrations.RemoveField(
            model_name='furnituremodernimages',
            name='modern',
        ),
        migrations.DeleteModel(
            name='FurnitureClassic',
        ),
        migrations.DeleteModel(
            name='FurnitureClassicImages',
        ),
        migrations.DeleteModel(
            name='FurnitureModern',
        ),
        migrations.DeleteModel(
            name='FurnitureModernImages',
        ),
    ]
