# Generated by Django 4.2.14 on 2024-07-19 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_furnitureclassicimages_classic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Furniture Category',
                'verbose_name_plural': 'Furniture Category',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('description', models.TextField(max_length=100000, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('image', models.ImageField(upload_to='Furniture/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_category', to='products.category', verbose_name='Furniture Category')),
            ],
            options={
                'verbose_name': 'Furnitures',
                'verbose_name_plural': 'Furnitures',
            },
        ),
    ]
