# Generated by Django 4.2.14 on 2024-07-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='furnitureimages/')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_images', to='products.furniture')),
            ],
            options={
                'verbose_name': 'Furniture Images ',
                'verbose_name_plural': 'Furniture Images ',
            },
        ),
    ]
